name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write  # This grants write permissions to the github-actions[bot]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          check-latest: true

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Build
        run: mkdocs build

      - name: List files in site directory
        run: ls -al ./site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
